FROM jakub-stastny/dev:latest

ENV SSHD_PORT=2222

# Environment variables
# Since the dev image is based on openssl-server rather than just docker run zsh,
# setting variables using the ENV directive won't help to propagate them out of
# this Dockerfile (although they might serve in the Dockerfile itself).

#RUN ...
